# Generated by Django 3.0.5 on 2020-05-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProSol_Plus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='ProSol_Plus/Solutions')),
                ('namefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProSol_Plus.UserFile')),
            ],
        ),
    ]
