# Generated by Django 3.0.5 on 2020-05-20 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProSol_Plus', '0005_auto_20200520_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 17, 39, 0, 362746)),
        ),
    ]
